version: '3'

services:
  web:
    build:
      context: ./backend  # Specify the build context as the backend directory
    
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8007"    volumes:
      - ./backend:/code  # Mount the backend directory to /code in the container
    ports:
    # 8007 to avoid conflicts
      - "8007:8007"
    # depends_on:
    #   - db   
    stdin_open: true
    tty: true

  # In case we want to create our own postgresql image
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"