# Generated by Django 4.0 on 2024-03-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amount_invested', models.FloatField()),
                ('investment_date', models.DateField(auto_now_add=True)),
                ('billing_type', models.CharField(default='Upfront fees', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('from_company', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('VALIDATED', 'Validated'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='VALIDATED', max_length=10)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('bill_type', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('validated', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investor')),
            ],
        ),
    ]
