# Generated by Django 5.0.3 on 2024-03-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('from_company', models.CharField(max_length=100)),
                ('to_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('VALIDATED', 'Validated'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='VALIDATED', max_length=10)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_type', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investor')),
            ],
        ),
    ]
